# Generated by Django 5.2.9 on 2025-12-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JngAsignatura',
            fields=[
                ('id_asignatura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_carrera', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'jng_asignatura',
            },
        ),
        migrations.CreateModel(
            name='JngAula',
            fields=[
                ('id_aula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jng_aula',
            },
        ),
        migrations.CreateModel(
            name='JngCarrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'jng_carrera',
            },
        ),
        migrations.CreateModel(
            name='JngContenido',
            fields=[
                ('id_contenido', models.IntegerField(primary_key=True, serialize=False)),
                ('id_asignatura', models.FloatField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'jng_contenido',
            },
        ),
        migrations.CreateModel(
            name='JngPeriodoAcademico',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('year_num', models.FloatField(blank=True, null=True)),
                ('semestre', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jng_periodo_academico',
            },
        ),
        migrations.CreateModel(
            name='JngPermiso',
            fields=[
                ('id_permiso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'jng_permiso',
            },
        ),
        migrations.CreateModel(
            name='JngRol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'jng_rol',
            },
        ),
        migrations.CreateModel(
            name='JngSede',
            fields=[
                ('id_sede', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'jng_sede',
            },
        ),
        migrations.CreateModel(
            name='JngTipoActividad',
            fields=[
                ('id_tipo_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'jng_tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='JngTipoEvaluacion',
            fields=[
                ('id_tipo_evaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'jng_tipo_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='JngUniversidad',
            fields=[
                ('id_universidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'jng_universidad',
            },
        ),
        migrations.CreateModel(
            name='JngAlumno',
            fields=[
                ('id_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngcarrera')),
            ],
            options={
                'db_table': 'jng_alumno',
            },
        ),
        migrations.CreateModel(
            name='JngNota',
            fields=[
                ('id_nota', models.IntegerField(primary_key=True, serialize=False)),
                ('id_evaluacion', models.FloatField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('id_alumno', models.ForeignKey(blank=True, db_column='id_alumno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngalumno')),
            ],
            options={
                'db_table': 'jng_nota',
            },
        ),
        migrations.CreateModel(
            name='JngPlanEstudios',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('year_inicio', models.FloatField(blank=True, null=True)),
                ('year_fin', models.FloatField(blank=True, null=True)),
                ('id_carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngcarrera')),
            ],
            options={
                'db_table': 'jng_plan_estudios',
            },
        ),
        migrations.CreateModel(
            name='JngSeccion',
            fields=[
                ('id_seccion', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.FloatField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('cupos', models.IntegerField(blank=True, null=True)),
                ('id_asignatura', models.ForeignKey(blank=True, db_column='id_asignatura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngasignatura')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngperiodoacademico')),
            ],
            options={
                'db_table': 'jng_seccion',
            },
        ),
        migrations.CreateModel(
            name='JngInscripcion',
            fields=[
                ('id_inscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_alumno', models.ForeignKey(blank=True, db_column='id_alumno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngalumno')),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
            ],
            options={
                'db_table': 'jng_inscripcion',
            },
        ),
        migrations.CreateModel(
            name='JngHorario',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('id_aula', models.ForeignKey(blank=True, db_column='id_aula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngaula')),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
            ],
            options={
                'db_table': 'jng_horario',
            },
        ),
        migrations.AddField(
            model_name='jngcarrera',
            name='id_sede',
            field=models.ForeignKey(blank=True, db_column='id_sede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngsede'),
        ),
        migrations.AddField(
            model_name='jngaula',
            name='id_sede',
            field=models.ForeignKey(blank=True, db_column='id_sede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngsede'),
        ),
        migrations.CreateModel(
            name='JngActividad',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
                ('id_tipo_actividad', models.ForeignKey(blank=True, db_column='id_tipo_actividad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngtipoactividad')),
            ],
            options={
                'db_table': 'jng_actividad',
            },
        ),
        migrations.CreateModel(
            name='JngEvaluacion',
            fields=[
                ('id_evaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
                ('id_tipo_evaluacion', models.ForeignKey(blank=True, db_column='id_tipo_evaluacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngtipoevaluacion')),
            ],
            options={
                'db_table': 'jng_evaluacion',
            },
        ),
        migrations.AddField(
            model_name='jngsede',
            name='id_universidad',
            field=models.ForeignKey(blank=True, db_column='id_universidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jnguniversidad'),
        ),
        migrations.CreateModel(
            name='JngUsuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('rut', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngrol')),
            ],
            options={
                'db_table': 'jng_usuario',
            },
        ),
        migrations.CreateModel(
            name='JngMensajeInterno',
            fields=[
                ('id_mensaje', models.IntegerField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(blank=True, max_length=4000, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_usuario_envia', models.ForeignKey(blank=True, db_column='id_usuario_envia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
                ('id_usuario_recibe', models.ForeignKey(blank=True, db_column='id_usuario_recibe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jngmensajeinterno_id_usuario_recibe_set', to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_mensaje_interno',
            },
        ),
        migrations.CreateModel(
            name='JngMaterialCurso',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('fecha_subida', models.DateField(blank=True, null=True)),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_material_curso',
            },
        ),
        migrations.CreateModel(
            name='JngLogUserAdmin',
            fields=[
                ('id_log_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_accion', models.DateTimeField(blank=True, null=True)),
                ('detalles', models.CharField(blank=True, max_length=2000, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_log_user_admin',
            },
        ),
        migrations.CreateModel(
            name='JngLogAutenticacion',
            fields=[
                ('id_log_auth', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_intento', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_log_autenticacion',
            },
        ),
        migrations.AddField(
            model_name='jngcarrera',
            name='id_director',
            field=models.ForeignKey(blank=True, db_column='id_director', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario'),
        ),
        migrations.CreateModel(
            name='JngAyudantia',
            fields=[
                ('id_ayudantia', models.IntegerField(primary_key=True, serialize=False)),
                ('id_carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngcarrera')),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_ayudantia',
            },
        ),
        migrations.CreateModel(
            name='JngAsignacionSecretaria',
            fields=[
                ('id_asignacion_secretaria', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('id_sede', models.ForeignKey(blank=True, db_column='id_sede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngsede')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_asignacion_secretaria',
            },
        ),
        migrations.CreateModel(
            name='JngAsignacionDocente',
            fields=[
                ('id_asignacion_docente', models.IntegerField(primary_key=True, serialize=False)),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_asignacion_docente',
            },
        ),
        migrations.CreateModel(
            name='JngAnuncio',
            fields=[
                ('id_anuncio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('contenido', models.CharField(blank=True, max_length=4000, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngcarrera')),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngseccion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario')),
            ],
            options={
                'db_table': 'jng_anuncio',
            },
        ),
        migrations.AddField(
            model_name='jngalumno',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngusuario'),
        ),
        migrations.CreateModel(
            name='JngAsignaturaCarrera',
            fields=[
                ('semestre', models.FloatField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngasignatura')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngplanestudios')),
            ],
            options={
                'db_table': 'jng_asignatura_carrera',
                'unique_together': {('id_plan', 'id_asignatura')},
            },
        ),
        migrations.CreateModel(
            name='JngPrerequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.jngasignatura')),
                ('id_asignatura_req', models.ForeignKey(db_column='id_asignatura_req', on_delete=django.db.models.deletion.DO_NOTHING, related_name='jngprerequisito_id_asignatura_req_set', to='api.jngasignatura')),
            ],
            options={
                'db_table': 'jng_prerequisito',
                'unique_together': {('id_asignatura', 'id_asignatura_req')},
            },
        ),
    ]
