# Generated by Django 5.2.8 on 2025-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JngRolPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jng_rol_permiso',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='jngactividad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngalumno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jnganuncio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngasignaciondocente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngasignacionsecretaria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngasignatura',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngasignaturacarrera',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngaula',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngayudantia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngcarrera',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngcontenido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngevaluacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jnghorario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jnginscripcion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jnglogautenticacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngloguseradmin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngmaterialcurso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngmensajeinterno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngnota',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngperiodoacademico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngpermiso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngplanestudios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngprerequisito',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngrol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngseccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngsede',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngtipoactividad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngtipoevaluacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jnguniversidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jngusuario',
            options={'managed': False},
        ),
    ]
